### ISSUE TITLE
Two memory issues

### ISSUE THREAD

**Issue by jhwangbo** [OGRECave/ogre-assimp#10]
I am using ogre-assimp in my project. I spotted two major issues in this code. 

1. Meshes are not loaded. This causes the whole memory to be leaked when deleted. I solved this issue by adding 
`    for(auto mesh: mMeshes)
       mesh->load();`
at the end of convert() function.

2. createSubMesh() assumes that all faces have 3 indices. But sometimes I get meshes with even two indices and it reads a wrong part of the memory. Does anyone know what does a face with two indices mean? anyway, I solved it by just setting all indices to zero when this happens. Very hacky but it works for me.

My code is available here: https://github.com/leggedrobotics/raisimOgre

**Comment by paroj** [comment]
thanks for investigating. Can you provide a pull-request for us?
