### ISSUE TITLE
still Invalid Memory Write error from valgrind

### ISSUE THREAD

**Issue by jhwangbo** [OGRECave/ogre-assimp#12]
Version 1.12.2
Os Linux
Render System: Opengl

Dear Ogre developers

I am working on the raisim library. Recently I spotted either Ogre or OgreAssimp is corrupting the memory of the simulation library. Running valgrind gives me "Invalid write" error on [here](https://github.com/OGRECave/ogre-assimp/blob/940e8fa46502d0579bd663c5cb72d6f5e0e0a89e/src/AssimpLoader.cpp#L1427)

I know this is the one I pushed but I cannot figure out what is wrong here. I build everything debug and checked all memory allocations from Ogre and OgreAssimp and couldn't find any mistakes. But I keep getting the errors from valgrind. This can be a false alert but I see the effects of invalid memory write in my applications and this is the most suspicious location. The same code without visualization works fine and valgrind clean as well.

I spent at least one full week on debugging this without much success. I will appreciate if more experienced people can take a look at it

Jemin

**Comment by paroj** [comment]
a quick glance suggest that you should also do `i++` in the `if(faces->mNumIndices != 3)` case - as there is exactly `mesh->mNumFaces * 3` space in `indexData`

**Comment by jhwangbo** [comment]
No that didn't help. I am not sure why you think `i` should be incremented but it doesn't make sense to me. I deleted the 16-bit index part and keep everything 32-bit then I don't see the memory issue anymore. But then I get invalid write error again on vertex buffer. This seems to me like ogreHardwareBuffer/Manager bug to me. I'll investigate a bit more.

**Comment by paroj** [comment]
Can you attach a test model, that triggers that crash?

**Comment by paroj** [comment]
should be fixed by cd8aac12fabb82d63901ef462eb7157820e4f25c
