### ISSUE TITLE
Level of Detail levels explanation

### ISSUE THREAD

**Issue by waseemkhan1989** [OGRECave/ogre-assimp#8]
Hi,
I want to convert a file with option "Level of Detail level(lod levels)" enabled. I want to know whether assimp converter automatically handles all lod levels of the existing model or can I specify a specific lod level for the converion? Could you provide any documentation on lod levels that what factors should I keep in mind while converting such files?
Some files are not supported like .DWG, .igs, .jt, .stp and .zgl on this converter. Could you please also mention, which files are supported on this converter?
Thanks in advance.

Best,
Waseem Khan

**Comment by waseemkhan1989** [comment]
@paroj  @JRK80 Could you guys please comment on the above mentioned issue?

**Comment by paroj** [comment]
see https://ogrecave.github.io/ogre/api/latest/meshlod-generator.html
