### ISSUE TITLE
bad allocation message

### ISSUE THREAD

**Issue by waseemkhan1989** [OGRECave/ogre-assimp#9]
Hi, 

I am getting the following error message while converting a file:

D:\cpp\projects\ogre-assimp\build\x86\Release>OgreAssimpConverter.exe FTF_small.FBX

-- OPTIONS --
source file               = FTF_small.FBX
destination               =
animation speed modifier  = 1
log file                  = ass.log
-- END OPTIONS --

Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
Registering ResourceManager for type Mesh
Registering ResourceManager for type Material
Registering ResourceManager for type Skeleton
ArchiveFactory for archive type FileSystem registered.
*** Loading ass file... ***
Filename FTF_small.FBX
Added resource location '' of type 'FileSystem' to resource group 'General'
Added resource location './resources' of type 'FileSystem' to resource group 'General'
Parsing scripts for resource group General
Finished parsing scripts for resource group General
Creating resources for group General
All done
Parsing scripts for resource group OgreAutodetect
Finished parsing scripts for resource group OgreAutodetect
Creating resources for group OgreAutodetect
All done
Parsing scripts for resource group OgreInternal
Finished parsing scripts for resource group OgreInternal
Creating resources for group OgreInternal
All done
AssImp importer failed with the following message:
bad allocation
Unregistering ResourceManager for type Skeleton
Unregistering ResourceManager for type Material

Any help in this regard?

**Comment by paroj** [comment]
need the fbx file for reproduction
